//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHolaKingdom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int id { get; set; }
        public Nullable<int> blog_category_id { get; set; }
        public int user_id { get; set; }
        public string title { get; set; }
        public string brief_infor { get; set; }
        public string description { get; set; }
        public string Image { get; set; }
        public string banner { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual BlogsCategory BlogsCategory { get; set; }
    }
}
