//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHolaKingdom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int id { get; set; }
        public string Description { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public double Weight { get; set; }
        public string Gender { get; set; }
        public int PetCategoryId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual PetsHistory PetsHistory { get; set; }
    }
}
