//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHolaKingdom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LessonDetailId { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual LessonDetail LessonDetail { get; set; }
        public virtual User User { get; set; }
    }
}
